name: pagarme_card_hash_generator
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  card_hash_generator: ^0.0.3+hotfix.2
  mask_text_input_formatter: ^2.1.0
  url_launcher: ^6.0.20
  url_strategy: ^0.2.0
  seo_renderer: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/

scripts:
  clean: flutter clean
  get: flutter pub get
  build: flutter clean & flutter build web --web-renderer html
  deploy: firebase deploy --only hosting